In [40]:
#Author Quentin Picard
#Date 02/03/2020

## Imports

In [41]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import seaborn as sns
path = "csv_files"

## Exercice 1

In [42]:
df = pd.read_csv(path + 'house_pricing.csv')
print(df.dtypes)
df[(df['LotArea'] < 20000) & (df['SalePrice'] < 500000)].plot.scatter(x='LotArea', y='SalePrice')
df[(df['LotArea'] < 100000) & (df['LotFrontage'] < 200)].plot.scatter(x='LotArea', y='LotFrontage')

FileNotFoundError: [Errno 2] No such file or directory: 'csv_fileshouse_pricing.csv'

## Exercice 2

In [43]:
df = pd.read_csv(path + 'sales_predictions.csv')
print(df.dtypes)
df

FileNotFoundError: [Errno 2] No such file or directory: 'csv_filessales_predictions.csv'

In [44]:
sns.set(style="ticks")
#mpl.pyplot.figure(figsize=[20,6])
g = sns.relplot(x='date', y='item_price', data=df)
fig = mpl.pyplot.gcf()
fig.set_size_inches(20,6)
g = sns.relplot(x='date', y='item_price', data=df.sample(500))
fig = mpl.pyplot.gcf()
fig.set_size_inches(20,6)
df['date'] =  pd.to_datetime(df['date'], format='%d.%m.%Y')
g = sns.relplot(x='date', y='item_price', data=df.sample(500))
fig = mpl.pyplot.gcf()
fig.set_size_inches(20,6)

NameError: name 'df' is not defined

## Exercice 3

In [45]:
df = pd.read_csv(path + 'IBM_HR_ATTRITION.csv')
print(df.dtypes)
df

FileNotFoundError: [Errno 2] No such file or directory: 'csv_filesIBM_HR_ATTRITION.csv'

In [46]:
g = sns.catplot(x="Attrition", y="JobSatisfaction", kind='bar' ,data=df)

NameError: name 'df' is not defined

In [47]:
g = sns.boxplot(x="Attrition", y="JobSatisfaction", data=df)

NameError: name 'df' is not defined

In [48]:
g = sns.catplot(x="Attrition", y="TotalWorkingYears", kind='bar' ,data=df)

NameError: name 'df' is not defined

In [49]:
g = sns.boxplot(x="Attrition", y="TotalWorkingYears", data=df)

NameError: name 'df' is not defined

In [50]:
df.describe()

NameError: name 'df' is not defined

In [51]:
df[((df['TotalWorkingYears'] > 20) & (df['Attrition'])) | ((df['TotalWorkingYears'] > 32) & (df['Attrition'] == False))].describe()

NameError: name 'df' is not defined

## Exercice 4

In [52]:
df = pd.read_csv(path + 'IBM_HR_ATTRITION.csv')
print(df.dtypes)
df

FileNotFoundError: [Errno 2] No such file or directory: 'csv_filesIBM_HR_ATTRITION.csv'

In [53]:
sns.distplot(df['MonthlyIncome'], vertical=True)
sns.distplot(df[df['MonthlyIncome'] < 5000]['MonthlyIncome'], vertical=True)

NameError: name 'df' is not defined

## Exercice 5

In [54]:
df = pd.read_csv(path + 'IBM_HR_ATTRITION.csv')
print(df.dtypes)
df

FileNotFoundError: [Errno 2] No such file or directory: 'csv_filesIBM_HR_ATTRITION.csv'

In [55]:
df['Temp'] = df['Attrition'].map({'Yes': 1, 'No': 0})
df.drop(columns=['Attrition'])
df['Attrition'] = df['Temp']
df.drop(columns=['Temp'])
df

NameError: name 'df' is not defined

In [56]:
g = sns.lmplot(x="Attrition", y="DistanceFromHome", data=df.sample(50))

NameError: name 'df' is not defined

In [57]:
g = sns.lmplot(x="Attrition", y="YearsWithCurrManager", data=df.sample(50))

NameError: name 'df' is not defined

## Exercice 6

In [58]:
df = pd.read_csv(path + 'house_pricing.csv')
print(df.dtypes)
df

FileNotFoundError: [Errno 2] No such file or directory: 'csv_fileshouse_pricing.csv'

In [59]:
df.iloc[:,-15:]

NameError: name 'df' is not defined

In [60]:
df.corr()

NameError: name 'df' is not defined

In [61]:
#g = mpl.pyplot.matshow(df.corr())
g = sns.heatmap(df.corr())

NameError: name 'df' is not defined

Top 3 des features : 
    -LotArea
    -YearBuilt
    -BsmtFinSF1

## Numpy

In [62]:
l = [x for x in range(10) if not x%2]

In [63]:
l

[0, 2, 4, 6, 8]

In [64]:
l[0]

0

In [65]:
l[-1]

8

In [66]:
ar = np.array([x for x in range(10) if not x%2])

In [67]:
ar

array([0, 2, 4, 6, 8])

In [68]:
ar.mean()

4.0

In [69]:
ar.max()

8

In [70]:
ar.argmax()

4

In [71]:
ar[0]

0

In [72]:
ar2 = np.array([[1, 2],[3, 4]])
ar2

array([[1, 2],
       [3, 4]])

In [73]:
ar.sum()

20

In [74]:
ar2.sum()

10

In [75]:
type(ar)

numpy.ndarray

In [76]:
ar2.sum(axis=0)

array([4, 6])

In [77]:
ar2.sum(axis=1)

array([3, 7])